### ISSUE TITLE
Plugin doesn't appear in game

### ISSUE THREAD

**Issue by boomam** [oli414/CheatSaver#5]
Hi,
Installed the latest version of the plugin as of now, latest OpenRCT2 as well - plugin does not appear in maps menu as mentioned in documentation.  

Are additional steps required for usage, or is this a known issue or incompatibility with other plugins?

Thanks!

**Comment by oli414** [comment]
Hi! That's odd, it should work, I'm using it myself right now.

Can you check what version you're using. there's a possibility that the plugin is not compatible experimental new save file format version (which you can only download through Github).

Additionally, it's possible that the latest stable release is not supported. Most people tend to play on develop.

Can you check which version you're using?

**Comment by boomam** [comment]
Sure - 
I'm using v0.3.3 (3f65f28) - the latest stable as of today.
And the following other plugins are in use (all up-to-date as of today) - 

- benchwarmer
- live ride measurements
- random balloon colours
- ride price manager
- soft guest cap calculator

Thanks!

**Comment by oli414** [comment]
Odd, this plugin hasn't needed an update so it should work on both develop and release.

It's possible that you installed the wrong file.
https://github.com/oli414/CheatSaver/releases/tag/1.0
Can you download the .js file from this page, and remove the old file you have in `OpenRCT/plugins`?

**Comment by boomam** [comment]
Just tested, that appears to have worked! :-)

The download I originally used was this: https://github.com/oli414/CheatSaver/blob/master/build/CheatSaver.js

**Comment by oli414** [comment]
Aha, that folder shouldn't be there, it has since been added to the gitignore. I'll remove it!

**Comment by boomam** [comment]
Thank you for responding quickly and resolving! :-)

**Comment by oli414** [comment]
Thanks, looks like the readme was outdated as well so I've fixed that now. Have fun!
